server:
  port: 8085

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task
    username: root
    password: Zzq664450274
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /static/**
logging:
  level:
    root: warn
mybatis:
  configuration:
    call-setters-on-nulls: true